@startuml
:用户: as U
:销售员:  as S
:销售管理员: as SK
:仓库管理员: as WK

U <|-- S
U <|-- SK
U <|-- WK

U -u-> (登录)
U -u-> (登出)

S -> (查询自己签订合同的执行情况)
S --> (查询一段时间内自己的销售业绩)

SK --> (生成发货单)
SK --> (管理合同信息)
SK --> (管理客户信息)
SK -up-> (管理销售人员信息)
SK -up-> (统计销售额)
(统计销售额) <|-up- (统计一段时间内公司的销售总额)
(统计销售额) <|-- (统计一段时间内不同客户的销售额)
(统计销售额) <|-- (统计一段时间内不同商品的销售额)

WK -up-> (确认发货单)
WK --> (记录相关物流信息)
WK -left-> (进货)
WK -> (记录进货信息)
WK --> (修改对应商品的库存)

@enduml